services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    networks:
      - app-net
    volumes:
      - ${PWD}/DB/cql_scripts:/app
      - ${PWD}/DB/volume:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 10s
      timeout: 5s
      retries: 10

  cqlsh-init:
    image: nuvo/docker-cqlsh
    container_name: cqlsh-init
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - CQLSH_HOST=cassandra
      - CQLSH_PORT=9042
      - CQLVERSION=3.4.7
    networks:
      - app-net

  kafka1:
    image: apache/kafka:latest
    container_name: kafka1
    hostname: kafka1
    ports:
      - "29092:29092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller

      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,EXTERNAL://localhost:29092

      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL

      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093

      - CLUSTER_ID=MkU3OEVBNTcwNTJDRDRCMz
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2

    volumes:
      - ${PWD}/MessageQueue/kafka1:/var/lib/kafka/data
    networks:
      - app-net

  kafka2:
    image: apache/kafka:latest
    container_name: kafka2
    hostname: kafka2
    ports:
      - "29093:29093"
    environment:
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker,controller

      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29093,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,EXTERNAL://localhost:29093

      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL

      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093

      - CLUSTER_ID=MkU3OEVBNTcwNTJDRDRCMz
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=2

    volumes:
      - ${PWD}/MessageQueue/kafka2:/var/lib/kafka/data
    networks:
      - app-net

  kafka-init:
    image: apache/kafka:latest
    container_name: kafka-init
    depends_on:
      - kafka1
      - kafka2
    networks:
      - app-net
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      sleep 25;
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka1:9092 --create --if-not-exists --topic fcm --partitions 3 --replication-factor 2
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka1:9092 --create --if-not-exists --topic email --partitions 3 --replication-factor 2
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka1:9092 --create --if-not-exists --topic apn --partitions 3 --replication-factor 2
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka1:9092 --create --if-not-exists --topic dlq --partitions 3 --replication-factor 2
      echo 'Kafka topics created';
      "

networks:
  app-net:
    name: notification-network